(() => {
  'use strict';
  const site=window.SOFTBALL_SITE,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  if(!site)return;
  const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const isCalendar=document.body.dataset.page==='calendar';
  let events=[],mine=[],session={signedIn:false,canManage:false},type='All',view='month',selectedId='',editing=null,attendanceRows=[],windowOpenEditor=()=>{};
  const dateToday=new Intl.DateTimeFormat('en-CA',{timeZone:site.calendar.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  let displayed=new Date(dateToday+'T12:00:00Z');displayed.setUTCDate(1);
  const label={going:'Going',maybe:'Maybe',unavailable:'Unavailable'};
  const myResponse=id=>mine.find(r=>r.event_id===id);
  const dateValue=s=>new Date(s+'T12:00:00Z');
  const dateFormat=(s,opts={month:'short',day:'numeric',year:'numeric'})=>dateValue(s).toLocaleDateString('en-US',{...opts,timeZone:'UTC'});
  const range=e=>e.startDate===e.endDate?dateFormat(e.startDate):`${dateFormat(e.startDate,{month:'short',day:'numeric'})} – ${dateFormat(e.endDate)}`;
  const time=t=>{if(!t)return '';const [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`;};
  const timing=e=>e.allDay?'All day · timing to be confirmed':`${time(e.startTime)} – ${time(e.endTime)} MT`;
  const typeClass=e=>'type-'+e.type.toLowerCase().replace(/\s+/g,'-');
  const mapLink=e=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(e.location);
  const googleLink=e=>{const compact=s=>s.replace(/-/g,'');let dates;if(e.allDay){const d=dateValue(e.endDate);d.setUTCDate(d.getUTCDate()+1);dates=compact(e.startDate)+'/'+compact(d.toISOString().slice(0,10));}else dates=compact(e.startDate)+'T'+e.startTime.replace(':','')+'00/'+compact(e.endDate)+'T'+e.endTime.replace(':','')+'00';return 'https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:e.name,dates,ctz:site.calendar.timezone,location:e.location,details:(e.preview?'Illustrative sample event. ':'')+e.description}).toString();};
  async function request(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});const data=await response.json().catch(()=>({error:'The calendar service could not be reached.'}));if(!response.ok)throw new Error(data.error||'The calendar service could not be reached.');return data;}
  async function refresh(){const data=await request('/api/events');events=data.events;mine=data.mine;session=data.session;return data;}
  const text=(s,value)=>$$(s).forEach(el=>el.textContent=value);
  text('[data-team-name]',site.brand.teamName);text('[data-team-mark]',site.brand.mark);text('[data-team-subtitle]',site.brand.subtitle);text('[data-season]',site.brand.season);text('[data-timezone]',site.calendar.timezone);
  document.title=(isCalendar?'Calendar':'RSVP')+' | '+site.brand.teamName;
  Object.entries(site.brand.colors||{}).forEach(([k,v])=>{if(/^#[\da-f]{3,8}$/i.test(v))document.documentElement.style.setProperty('--'+k,v);});
  const menu=$('[data-mobile-menu]'),menuButton=$('[data-menu-button]');
  const closeMenu=()=>{menu.hidden=true;menuButton.setAttribute('aria-expanded','false');$('.sr-only',menuButton).textContent='Open navigation';};
  menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menu.hidden=open;menuButton.setAttribute('aria-expanded',String(!open));$('.sr-only',menuButton).textContent=open?'Open navigation':'Close navigation';});
  $$('a',menu).forEach(a=>a.addEventListener('click',closeMenu));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){closeMenu();menuButton.focus();}});
  document.addEventListener('click',e=>{if(!menu.hidden&&!$('[data-header]').contains(e.target))closeMenu();});
  matchMedia('(min-width:821px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
  $$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  $$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
  function showLoadError(error){const box=$('[data-load-error]');box.hidden=false;box.innerHTML=`${esc(error.message)} <button class="small-button" type="button" data-retry-load>Try again</button>`;$('[data-retry-load]',box).addEventListener('click',load);}
  function renderMonth(){
    const monthStart=displayed.toISOString().slice(0,10),last=new Date(Date.UTC(displayed.getUTCFullYear(),displayed.getUTCMonth()+1,0,12)),monthEnd=last.toISOString().slice(0,10);
    const filtered=events.filter(e=>type==='All'||e.type===type),visible=filtered.filter(e=>e.startDate<=monthEnd&&e.endDate>=monthStart);
    text('[data-month-heading]',displayed.toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'}));
    const first=new Date(displayed);first.setUTCDate(first.getUTCDate()-first.getUTCDay());const cells=Math.ceil((displayed.getUTCDay()+last.getUTCDate())/7)*7;
    let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="weekday">${x}</div>`).join('');
    for(let i=0;i<cells;i++){const day=new Date(first);day.setUTCDate(first.getUTCDate()+i);const key=day.toISOString().slice(0,10),outside=day.getUTCMonth()!==displayed.getUTCMonth();
      const dayEvents=filtered.filter(e=>e.startDate<=key&&e.endDate>=key);
      html+=`<div class="day-cell ${outside?'outside':''} ${key===dateToday?'is-today':''}"><time class="day-label" datetime="${key}" ${key===dateToday?'aria-current="date"':''}>${day.getUTCDate()}</time>${dayEvents.map(e=>`<button type="button" class="day-event ${typeClass(e)} ${myResponse(e.id)?'has-rsvp':''} ${e.cancelled?'is-cancelled':''}" data-open-event="${esc(e.id)}" aria-label="${esc(e.name+', '+dateFormat(key)+(e.cancelled?', cancelled':'')+(myResponse(e.id)?', your response: '+label[myResponse(e.id).status]:''))}"><strong class="event-full">${esc(e.name)}</strong><span class="event-short" aria-hidden="true">${({Tournament:'TOUR',Showcase:'SHOW',Practice:'PRAC',Game:'GAME','Team event':'TEAM'})[e.type]}</span><span class="event-time">${e.allDay?esc(e.type):esc(time(e.startTime))}</span></button>`).join('')}</div>`;
    }
    $('[data-month-grid]').innerHTML=html;$('[data-month-grid]').hidden=view!=='month';$('[data-agenda]').hidden=view!=='agenda';
    $('[data-agenda]').innerHTML=visible.length?visible.map(e=>`<article class="agenda-row"><div class="agenda-day"><small>${esc(dateFormat(e.startDate,{month:'short'}).toUpperCase())}</small>${dateValue(e.startDate).getUTCDate()}</div><div><button class="agenda-title" type="button" data-open-event="${esc(e.id)}">${esc(e.name)}</button><p>${esc(range(e))} · ${esc(e.type)}${e.cancelled?' · CANCELLED':''}<br>${esc(e.location)}${myResponse(e.id)?`<br>Your response: ${label[myResponse(e.id).status]}`:''}</p></div><a class="small-button" href="/rsvp?event=${encodeURIComponent(e.id)}">${myResponse(e.id)?'Update RSVP':'RSVP'} ↗</a></article>`).join(''):'<p class="empty-state">No events match this month. Try another month or event type.</p>';
    $$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
  }
  function renderSidebar(){const e=events.find(e=>!e.cancelled&&e.endDate>=dateToday);$('[data-next-card]').innerHTML=e?`<span class="next-date">${esc(range(e).toUpperCase())}</span><h3>${esc(e.name)}</h3><p>${esc(e.location)}<br>${esc(e.type)}${e.preview?' · Sample event':''}</p><button class="button button-primary" type="button" data-open-event="${esc(e.id)}">Event details <span aria-hidden="true">↗</span></button>`:'<p>No upcoming events yet. Check back for the next team date.</p>';$('[data-create-event]').hidden=!session.canManage;const account=$('[data-calendar-account]');account.href=session.signedIn?'/signout-with-chatgpt?return_to=%2Fcalendar':'/signin-with-chatgpt?return_to=%2Fcalendar';account.textContent=session.signedIn?'Sign out':'Team sign in';}
  const facts=e=>`<dl class="event-facts"><dt>When</dt><dd>${esc(range(e))}<br>${esc(timing(e))}${e.arrivalTime?`<br>Arrive by ${esc(time(e.arrivalTime))} MT`:''}</dd><dt>Where</dt><dd>${esc(e.location)}<br><a href="${esc(mapLink(e))}" target="_blank" rel="noopener noreferrer">Open directions ↗</a></dd>${e.rsvpDeadline?`<dt>RSVP by</dt><dd>${esc(dateFormat(e.rsvpDeadline))} · end of day MT</dd>`:''}</dl>`;
  const stats=e=>`<div class="response-stats" aria-label="Attendance totals">${['going','maybe','unavailable'].map(s=>`<span><strong>${e.counts?.[s]?.responses||0}</strong>${label[s]}</span>`).join('')}<span><strong>${(e.counts?.going?.guests||0)+(e.counts?.maybe?.guests||0)}</strong>Guests</span></div>`;
  const stateNote=e=>e.cancelled?'This event has been cancelled.':e.rsvpState==='past'?'This event has ended.':e.rsvpState==='closed'?'The RSVP deadline has passed.':e.preview?'Illustrative sample event. Confirm the schedule with your team.':'';
  function openEvent(id,updateUrl=true){const e=events.find(x=>x.id===id);if(!e)return;const d=$('[data-event-dialog]');if(!d)return;
    $('[data-event-detail]').innerHTML=`<span class="event-type">${esc(e.type)}</span><h2 class="event-detail-title" id="event-dialog-title">${esc(e.name)}</h2>${facts(e)}<p class="event-description">${esc(e.description)}</p>${stateNote(e)?`<p class="event-status">${esc(stateNote(e))}</p>`:''}${stats(e)}<div class="event-actions">${e.rsvpState==='open'?`<a class="button button-primary" href="/rsvp?event=${encodeURIComponent(e.id)}">${myResponse(e.id)?'Update your RSVP':'RSVP to this event'} ↗</a>`:''}<a class="button button-dark" href="/calendar.ics?event=${encodeURIComponent(e.id)}">Download event</a></div><div class="event-tools">${!e.cancelled?`<a href="${esc(googleLink(e))}" target="_blank" rel="noopener noreferrer">Add to Google Calendar ↗</a>`:''}${session.canManage?`<button data-edit-event="${esc(e.id)}" type="button">Edit event</button><button data-view-attendance="${esc(e.id)}" type="button">View team responses</button>`:''}</div>`;
    if(!d.open)d.showModal();if(updateUrl){const u=new URL(location.href);u.searchParams.set('event',id);history.replaceState(null,'',u.pathname+u.search);}
  }
  function renderRsvp(){
    let available=events.filter(e=>e.endDate>=dateToday);const requested=events.find(e=>e.id===selectedId);if(requested&&!available.some(e=>e.id===requested.id))available.push(requested);
    if(!available.some(e=>e.id===selectedId))selectedId=(available.find(e=>e.rsvpState==='open')||available[0])?.id||'';
    text('[data-my-progress]',session.signedIn?`${available.filter(e=>myResponse(e.id)).length} of ${available.length} responses saved`:'Choose an event, then sign in to respond.');
    $('[data-rsvp-events]').innerHTML=available.length?available.map(e=>`<button type="button" class="event-choice" data-select-event="${esc(e.id)}" aria-pressed="${e.id===selectedId}"><span class="event-choice-date">${esc(range(e).toUpperCase())}</span><strong class="event-choice-title">${esc(e.name)}</strong><span class="event-choice-bottom"><span>${esc(e.type)}${e.cancelled?' · Cancelled':''}</span>${myResponse(e.id)?`<span class="response-label ${myResponse(e.id).status}">${label[myResponse(e.id).status]}</span>`:'<span>View event ↗</span>'}</span></button>`).join(''):'<p class="empty-state">No upcoming events yet. Check the full calendar for past dates.</p>';
    const e=events.find(e=>e.id===selectedId);if(!e){$('[data-rsvp-panel]').innerHTML='<p class="empty-state">The next team dates will appear here.</p>';return;}
    const r=myResponse(e.id),signIn='/signin-with-chatgpt?return_to='+encodeURIComponent('/rsvp?event='+encodeURIComponent(e.id));
    const form=session.signedIn && e.rsvpState==='open'?`<form class="rsvp-form" data-rsvp-form><fieldset><legend>Will you be there?</legend><div class="response-options">${['going','maybe','unavailable'].map(s=>`<label class="response-option"><input type="radio" name="status" value="${s}" ${r?.status===s?'checked':''} required><strong>${label[s]}</strong><span>${s==='going'?"I’m in.":s==='maybe'?'Still working it out.':"Can’t make it."}</span></label>`).join('')}</div></fieldset><div class="form-grid"><label>Player / family name<input name="displayName" maxlength="80" autocomplete="name" value="${esc(r?.display_name||'')}" required placeholder="First name and last initial"></label><label>Additional guests<select name="guests">${Array.from({length:11},(_,i)=>`<option value="${i}" ${r?.guests===i?'selected':''}>${i}${i===0?' — just the player':''}</option>`).join('')}</select></label><label class="full-field">Note for the team (optional)<textarea name="note" rows="3" maxlength="1000" placeholder="Arriving late, a ride needed, or anything the team should know.">${esc(r?.note||'')}</textarea></label></div><p class="form-hint">One response per account for this event. Your name and note are visible only to you and the site owner. Keep sensitive player information out of notes.</p><p class="form-message" data-rsvp-message role="status"></p><div class="form-actions"><button class="button button-dark" type="submit">${r?'Update response':'Save my RSVP'} <span aria-hidden="true">↗</span></button>${r?'<button class="text-button" data-withdraw type="button">Remove my response</button>':''}</div></form>`:!session.signedIn && e.rsvpState==='open'?`<div class="sign-in-card"><h3>SAVE YOUR SPOT.</h3><p>Sign in with ChatGPT to save your response and come back to update it. The calendar stays public.</p><a class="button button-dark" href="${esc(signIn)}" target="_top">Sign in to RSVP ↗</a></div>`:'';
    $('[data-rsvp-panel]').innerHTML=`<span class="event-type">${esc(e.type)}</span><h2>${esc(e.name)}</h2>${facts(e)}${e.description?`<p class="event-description">${esc(e.description)}</p>`:''}${stateNote(e)?`<p class="event-status">${esc(stateNote(e))}</p>`:''}${stats(e)}${r?`<div class="saved-response"><p><strong>Your response: ${label[r.status]}</strong>Saved for ${esc(r.display_name)}</p><span>${esc(new Date(r.updated_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:site.calendar.timezone}))} MT</span></div>`:''}${form}<div class="event-tools"><a href="/calendar?event=${encodeURIComponent(e.id)}">Event details</a><a href="/calendar.ics?event=${encodeURIComponent(e.id)}">Download event</a>${!e.cancelled?`<a href="${esc(googleLink(e))}" target="_blank" rel="noopener noreferrer">Google Calendar ↗</a>`:''}${session.signedIn?'<a href="/signout-with-chatgpt?return_to=%2Frsvp" target="_top">Sign out</a>':''}</div>`;
    const f=$('[data-rsvp-form]');if(f){f.addEventListener('submit',saveRsvp);const updateGuests=()=>{const unavailable=f.elements.namedItem('status').value==='unavailable';f.elements.namedItem('guests').disabled=unavailable;};$$('[name=status]',f).forEach(b=>b.addEventListener('change',updateGuests));updateGuests();$('[data-withdraw]',f)?.addEventListener('click',withdraw);}
  }
  function message(selector,value,kind){const el=$(selector);if(el){el.textContent=value;el.className='form-message '+kind;}}
  async function saveRsvp(ev){ev.preventDefault();const form=ev.currentTarget,id=selectedId,button=$('[type=submit]',form),fields=new FormData(form);button.disabled=true;message('[data-rsvp-message]','Saving your response…','');
    try{const result=await request('/api/rsvp',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:id,status:fields.get('status'),displayName:fields.get('displayName'),guests:Number(fields.get('guests')||0),note:fields.get('note')})});mine=mine.filter(r=>r.event_id!==id);mine.push(result.response);let refreshed=true;try{await refresh();}catch{refreshed=false;}renderRsvp();if(selectedId===id)message('[data-rsvp-message]',refreshed?'Your response is saved. You can update it here before the deadline.':'Your response is saved. Reload to refresh the attendance totals.','success');}
    catch(error){message('[data-rsvp-message]',error.message,'error');button.disabled=false;}
  }
  async function withdraw(){const form=$('[data-rsvp-form]'),b=$('[data-withdraw]',form),id=selectedId;b.disabled=true;message('[data-rsvp-message]','Removing your response…','');try{await request('/api/rsvp',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:id})});mine=mine.filter(r=>r.event_id!==id);try{await refresh();}catch{}renderRsvp();message('[data-rsvp-message]','Your response was removed.','success');}catch(error){message('[data-rsvp-message]',error.message,'error');b.disabled=false;}}
  function render(){const sample=events.some(e=>e.preview);$('[data-concept-note]').hidden=!sample;if(isCalendar){renderMonth();renderSidebar();}else renderRsvp();}
  async function load(){try{await refresh();$('[data-load-error]').hidden=true;render();if(isCalendar){const id=new URL(location.href).searchParams.get('event');if(id)openEvent(id,false);}}catch(error){showLoadError(error);if(isCalendar){text('[data-month-heading]','Calendar unavailable');$('[data-next-card]').innerHTML='<p>The schedule could not be loaded.</p>';}else $('[data-rsvp-events]').innerHTML='<p class="empty-state">The schedule could not be loaded.</p>';}}
  document.addEventListener('click',e=>{const open=e.target.closest('[data-open-event]');if(open)openEvent(open.dataset.openEvent);const pick=e.target.closest('[data-select-event]');if(pick){selectedId=pick.dataset.selectEvent;const u=new URL(location.href);u.searchParams.set('event',selectedId);history.replaceState(null,'',u.pathname+u.search);renderRsvp();}const edit=e.target.closest('[data-edit-event]');if(edit)openEditor(events.find(x=>x.id===edit.dataset.editEvent));const attendance=e.target.closest('[data-view-attendance]');if(attendance)openAttendance(attendance.dataset.viewAttendance);});
  if(isCalendar){
    $('[data-event-filters]').innerHTML=['All',...site.calendar.types].map(t=>`<button type="button" data-filter-type="${esc(t)}" aria-pressed="${t===type}">${esc(t)}</button>`).join('');
    $('[data-event-filters]').addEventListener('click',e=>{const b=e.target.closest('[data-filter-type]');if(!b)return;type=b.dataset.filterType;$$('[data-filter-type]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMonth();});
    $('[data-month-prev]').addEventListener('click',()=>{displayed.setUTCMonth(displayed.getUTCMonth()-1);renderMonth();});$('[data-month-next]').addEventListener('click',()=>{displayed.setUTCMonth(displayed.getUTCMonth()+1);renderMonth();});$('[data-today]').addEventListener('click',()=>{displayed=dateValue(dateToday);displayed.setUTCDate(1);renderMonth();});$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;renderMonth();}));
    $('[data-type-options]').innerHTML=site.calendar.types.map(t=>`<option>${esc(t)}</option>`).join('');
    const form=$('[data-event-form]');const syncTimes=()=>{$$('[data-time-field]').forEach(el=>el.hidden=form.elements.namedItem('allDay').checked);['startTime','endTime'].forEach(n=>form.elements.namedItem(n).required=!form.elements.namedItem('allDay').checked);};
    form.elements.namedItem('allDay').addEventListener('change',syncTimes);form.elements.namedItem('startDate').addEventListener('change',()=>{if(!form.elements.namedItem('endDate').value||form.elements.namedItem('endDate').value<form.elements.namedItem('startDate').value)form.elements.namedItem('endDate').value=form.elements.namedItem('startDate').value;});
    $('[data-create-event]').addEventListener('click',()=>openEditor(null));$('[data-cancel-editor]').addEventListener('click',()=>$('[data-manage-dialog]').close());
    form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),b=$('[type=submit]',form);b.disabled=true;message('[data-event-message]','Saving event…','');const data=Object.fromEntries(fd);data.allDay=fd.has('allDay');data.preview=fd.has('preview');data.cancelled=fd.has('cancelled');if(editing){data.id=editing.id;data.revision=editing.revision;}
      try{const result=await request('/api/events',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});editing=result.event;try{await refresh();}catch{message('[data-event-message]','Your event is saved. Close this editor and reload to refresh the calendar.','success');return;}render();$('[data-manage-dialog]').close();openEvent(result.event.id);}catch(error){message('[data-event-message]',error.message,'error');}finally{b.disabled=false;}
    });
    $('[data-export-attendance]').addEventListener('click',()=>{const csvCell=v=>'"'+String(/^[=+@\-\t\r]/.test(String(v))?"'"+v:v).replace(/"/g,'""')+'"';const csv=[['Player / family','Response','Guests','Note','Updated'],...attendanceRows.map(r=>[r.display_name,label[r.status],r.guests,r.note,r.updated_at])].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aftershock-attendance.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
    function localOpenEditor(event){editing=event;form.reset();for(const [key,value] of Object.entries(event||{startDate:dateToday,endDate:dateToday,type:'Practice',allDay:true})){const el=form.elements.namedItem(key);if(el){if(el.type==='checkbox')el.checked=!!value;else el.value=value??'';}}text('#manage-title',event?'EDIT EVENT.':'ADD AN EVENT.');message('[data-event-message]','','');$('[type=submit]',form).disabled=false;syncTimes();$('[data-event-dialog]').close();$('[data-manage-dialog]').showModal();}
    windowOpenEditor=localOpenEditor;
  }
  function openEditor(event){if(session.canManage)windowOpenEditor(event);}
  async function openAttendance(id){if(!session.canManage)return;const dialog=$('[data-attendance-dialog]');$('[data-event-dialog]').close();$('[data-export-attendance]').hidden=true;$('[data-attendance-content]').innerHTML='<p class="empty-state">Loading team responses…</p>';dialog.showModal();try{const data=await request('/api/attendance?event='+encodeURIComponent(id));attendanceRows=data.responses;$('[data-attendance-content]').innerHTML=attendanceRows.length?`<div class="table-wrap"><table class="attendance-table"><thead><tr><th scope="col">Player / family</th><th scope="col">Response</th><th scope="col">Guests</th></tr></thead><tbody>${attendanceRows.map(r=>`<tr><td>${esc(r.display_name)}${r.note?`<p>${esc(r.note)}</p>`:''}</td><td>${label[r.status]}</td><td>${r.guests}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">No responses saved for this event yet.</p>';$('[data-export-attendance]').hidden=!attendanceRows.length;}catch(error){$('[data-attendance-content]').innerHTML=`<p class="form-message error" role="alert">${esc(error.message)}</p>`;}}
  selectedId=new URL(location.href).searchParams.get('event')||'';
  load();
})();
