import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Miniflare} from 'miniflare';
const persistence=fs.mkdtempSync(path.join(os.tmpdir(),'aftershock-d1-'));
const options={modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-07-01',d1Databases:{DB:'calendar-test'},d1Persist:persistence,bindings:{ADMIN_EMAILS:'coach@example.test'}};
let mf=new Miniflare(options);
const base='https://calendar.test';
const player={'oai-authenticated-user-id':'family-1','oai-authenticated-user-email':'family@example.test'};
const other={'oai-authenticated-user-id':'family-2','oai-authenticated-user-email':'other@example.test'};
const coach={'oai-authenticated-user-id':'coach-1','oai-authenticated-user-email':'coach@example.test'};
async function call(url,method='GET',value,who={}){const response=await mf.dispatchFetch(base+url,{method,headers:{...who,...(value?{'Content-Type':'application/json',Origin:base}:{})},body:value?JSON.stringify(value):undefined});return {status:response.status,body:await response.json()};}
try {
  const db=await mf.getD1Database('DB');
  for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())for(const statement of fs.readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(statement.trim())await db.prepare(statement.trim()).run();
  assert.equal((await call('/api/events')).body.events.length,3);
  assert.equal((await call('/api/rsvp','PUT',{eventId:'fall-classic-2026'})).status,401);
  assert.equal((await call('/api/events','POST',{},player)).status,403);
  assert.equal((await call('/api/attendance?event=fall-classic-2026','GET',undefined,player)).status,403);
  const event={name:'QA practice',location:'Test field',type:'Practice',startDate:'2030-10-10',endDate:'2030-10-10',startTime:'18:00',endTime:'20:00',allDay:false,arrivalTime:'17:45',description:'Bring cleats.',rsvpDeadline:'2030-10-09',preview:true};
  const created=await call('/api/events','POST',event,coach);assert.equal(created.status,201);
  const id=created.body.event.id;
  assert.equal((await call('/api/events','POST',{...event,endTime:'17:00'},coach)).status,400);
  assert.equal((await call('/api/events','POST',{...event,startDate:'2030-02-30'},coach)).status,400);
  const payload={eventId:id,status:'going',displayName:'Avery M.',guests:2,note:'Private ride request.',userId:'spoofed'};
  assert.equal((await call('/api/rsvp','PUT',payload,player)).status,200);
  assert.equal((await call('/api/rsvp','PUT',payload,player)).status,200);
  const reread=await call('/api/events','GET',undefined,player);assert.equal(reread.body.mine.length,1);assert.equal(reread.body.mine[0].note,payload.note);assert.equal(reread.body.events.find(e=>e.id===id).counts.going.responses,1);
  const publicData=await call('/api/events');assert.deepEqual(publicData.body.mine,[]);assert(!JSON.stringify(publicData.body).includes('Private ride request'));assert(!JSON.stringify(publicData.body).includes('Avery M.'));
  await call('/api/rsvp','PUT',{...payload,status:'maybe',displayName:'Other family'},other);
  const team=await call('/api/attendance?event='+id,'GET',undefined,coach);assert.equal(team.body.responses.length,2);assert(team.body.responses.some(r=>r.note===payload.note));
  const updated=await call('/api/rsvp','PUT',{...payload,status:'unavailable',guests:8},player);assert.equal(updated.body.response.guests,0);
  assert.equal((await call('/api/rsvp','PUT',{...payload,guests:20},player)).status,400);
  const unsafe=await mf.dispatchFetch(base+'/api/rsvp',{method:'PUT',headers:{...player,'Content-Type':'application/json',Origin:'https://evil.test'},body:JSON.stringify(payload)});assert.equal(unsafe.status,403);
  const edit=await call('/api/events','PUT',{...created.body.event,name:'Updated practice'},coach);assert.equal(edit.status,200);
  assert.equal((await call('/api/events','PUT',{...created.body.event,name:'Stale overwrite'},coach)).status,409);
  const calendar=await mf.dispatchFetch(base+'/calendar.ics?event='+id);const ics=await calendar.text();assert(ics.includes('DTSTART;TZID=America/Denver:20301010T180000'));assert(!ics.includes(payload.note));
  const allDay=await mf.dispatchFetch(base+'/calendar.ics?event=fall-classic-2026');assert((await allDay.text()).includes('DTEND;VALUE=DATE:20261012'));
  assert.equal((await mf.dispatchFetch(base+'/calendar.ics?event=missing')).status,404);
  await mf.dispose();mf=new Miniflare(options);
  assert.equal((await call('/api/events','GET',undefined,player)).body.mine[0].status,'unavailable');
  assert.equal((await call('/api/events')).body.events.find(e=>e.id===id).name,'Updated practice');
  assert.equal((await call('/api/rsvp','DELETE',{eventId:id},player)).status,200);
  assert.equal((await call('/api/attendance?event='+id,'GET',undefined,coach)).body.responses.length,1);
  const cancel=await call('/api/events','PUT',{...edit.body.event,cancelled:true},coach);assert.equal(cancel.status,200);
  assert.equal((await call('/api/rsvp','PUT',payload,player)).status,409);
  const ended=await call('/api/events','POST',{...event,startDate:'2020-10-10',endDate:'2020-10-10',rsvpDeadline:''},coach);
  assert.equal((await call('/api/rsvp','PUT',{...payload,eventId:ended.body.event.id},player)).status,409);
  for(const route of ['/','/calendar','/rsvp','/calendar.js','/assets/images/hero.webp'])assert.equal((await mf.dispatchFetch(base+route)).status,200);
  console.log('PASS: persistence across restart, RSVP ownership, private attendance, sign-in/owner authorization, CSRF, idempotent updates, guest validation, scheduling conflicts, cancellation/deadlines, timed/all-day ICS, and page routes.');
} finally {await mf.dispose();fs.rmSync(persistence,{recursive:true,force:true});}
