import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {build} from 'esbuild';
const mobile=path.resolve(import.meta.dirname,'..'),root=path.resolve(mobile,'..');
const context={window:{}};vm.runInNewContext(fs.readFileSync(root+'/site.config.js','utf8'),context);
const config=context.window.SOFTBALL_SITE;
fs.rmSync(mobile+'/www',{recursive:true,force:true});fs.mkdirSync(mobile+'/www/assets',{recursive:true});
for(const f of ['index.html','app.css','sw.js'])fs.copyFileSync(mobile+'/src/'+f,mobile+'/www/'+f);
fs.writeFileSync(mobile+'/www/team-config.js','window.SOFTBALL_SITE='+JSON.stringify(config)+';\n');
fs.cpSync(root+'/assets/fonts',mobile+'/www/assets/fonts',{recursive:true});
fs.copyFileSync(root+'/assets/favicon.svg',mobile+'/www/assets/favicon.svg');
fs.cpSync(root+'/assets/app',mobile+'/www/assets/app',{recursive:true});
fs.writeFileSync(mobile+'/www/manifest.webmanifest',JSON.stringify({id:'/team-app',name:config.app.name+' Team',short_name:config.app.name,start_url:'/team-app',scope:'/',display:'standalone',orientation:'portrait-primary',background_color:'#081c35',theme_color:'#081c35',description:'The team calendar, RSVP attendance, and contact information.',icons:[{src:'/mobile/assets/app/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'/mobile/assets/app/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any'},{src:'/mobile/assets/app/icon-maskable.png',sizes:'512x512',type:'image/png',purpose:'maskable'}]},null,2));
await build({entryPoints:[mobile+'/src/app.js'],outfile:mobile+'/www/app.js',bundle:true,minify:true,format:'iife',target:['chrome108','safari15'],legalComments:'eof'});
const nativeIndex=fs.readFileSync(mobile+'/www/index.html','utf8');
fs.writeFileSync(mobile+'/www/web-index.html',nativeIndex);
fs.writeFileSync(mobile+'/www/index.html',nativeIndex.replaceAll('/mobile/','./'));
console.log('Built bundled Android/iOS/PWA frontend. No remote server.url wrapper.');
